# ── IAM execution role ────────────────────────────────────────────────────────

resource "aws_iam_role" "lambda_exec" {
  name = "${var.project_name}-lambda-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "lambda_policy" {
  name = "${var.project_name}-lambda-policy"
  role = aws_iam_role.lambda_exec.id

  policy = jsonencode({
    Version = "2012-10-17"
    # SSM + KMS statements are appended via `for` comprehensions so the
    # conditional yields a zero- or one-element list with a single concrete
    # object type (rather than [] vs [obj], which fails type inference).
    Statement = concat(
      [
        # CloudWatch Logs — required for Lambda to write logs
        {
          Effect = "Allow"
          Action = [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Resource = "arn:aws:logs:*:*:*"
        },
        # Comprehend — language detection (resource-level ARNs not supported)
        {
          Effect   = "Allow"
          Action   = ["comprehend:DetectDominantLanguage"]
          Resource = "*"
        },
        # CloudWatch — custom metrics for the HakiAI namespace
        {
          Effect   = "Allow"
          Action   = ["cloudwatch:PutMetricData"]
          Resource = "*"
        },
        # Bedrock — RAG via Knowledge Base + direct InvokeModel.
        # GetInferenceProfile is required to call Claude 4.x models, which
        # only support cross-region inference and are referenced by
        # inference-profile IDs like `us.anthropic.claude-haiku-4-5-...`.
        {
          Effect = "Allow"
          Action = [
            "bedrock:RetrieveAndGenerate",
            "bedrock:Retrieve",
            "bedrock:InvokeModel",
            "bedrock:ApplyGuardrail",
            "bedrock:GetInferenceProfile",
            "bedrock:ListInferenceProfiles",
          ]
          Resource = "*"
        },
        # DynamoDB — LangGraph checkpoint store (conversation memory).
        # Scoped strictly to the checkpoints table so the Lambda cannot
        # touch anything else in DynamoDB.
        {
          Effect = "Allow"
          Action = [
            "dynamodb:GetItem",
            "dynamodb:PutItem",
            "dynamodb:Query",
            "dynamodb:BatchWriteItem",
          ]
          Resource = var.checkpoints_table_arn
        },
        # S3 — read access on the data bucket's page-images/ prefix only.
        # Required so that presigned URLs generated by citations.py
        # actually resolve — S3 validates the signer's permissions when
        # the URL is used, not when it's signed. Without this, the URL
        # is "created" successfully but returns 403 to the browser.
        {
          Effect   = "Allow"
          Action   = ["s3:GetObject"]
          Resource = "${var.data_bucket_arn}/page-images/*"
        },
      ],
      # SSM — LangSmith API key fetch at cold start. Scoped to the one
      # parameter. Only present when tracing is enabled.
      [for arn in(var.langsmith_ssm_parameter_arn == "" ? [] : [var.langsmith_ssm_parameter_arn]) : {
        Effect   = "Allow"
        Action   = ["ssm:GetParameter"]
        Resource = arn
      }],
      # KMS — decrypt the SecureString with the AWS-managed SSM key.
      # ViaService condition keeps this usable only through SSM.
      [for arn in(var.langsmith_ssm_parameter_arn == "" ? [] : [var.langsmith_ssm_parameter_arn]) : {
        Effect   = "Allow"
        Action   = ["kms:Decrypt"]
        Resource = "*"
        Condition = {
          StringEquals = {
            "kms:ViaService" = "ssm.${var.aws_region}.amazonaws.com"
          }
        }
      }]
    )
  })
}

# ── Lambda dependency layer ──────────────────────────────────────────────────
# The Lambda runtime ships boto3 but not langgraph / langchain-core / langsmith.
# We install those deps into a layer at apply-time using uv, targeting Linux
# x86_64 wheels so native extensions (msgpack, ormsgpack, etc.) are compatible
# with the Lambda execution environment.
#
# chromadb is excluded via the `local` dependency group in pyproject.toml so
# `uv export --frozen` never emits it — keeps the layer under the 250MB cap.

resource "terraform_data" "lambda_layer_build" {
  # Rebuild whenever deps or the lock change.
  triggers_replace = {
    pyproject = filesha256("${path.module}/../../../backend/pyproject.toml")
    uvlock    = filesha256("${path.module}/../../../backend/uv.lock")
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -euo pipefail
      BUILD_DIR="${abspath(path.module)}/.layer-build/python"
      rm -rf "${abspath(path.module)}/.layer-build"
      mkdir -p "$BUILD_DIR"
      # Freeze the runtime deps only (no dev or local groups).
      uv export \
        --project "${abspath("${path.module}/../../../backend")}" \
        --frozen --no-emit-project --no-dev \
        -o /tmp/haki-lambda-reqs.txt
      # Install into the layer dir with Linux x86_64 wheels so msgpack et al. work.
      uv pip install \
        -r /tmp/haki-lambda-reqs.txt \
        --target "$BUILD_DIR" \
        --python-platform x86_64-manylinux2014 \
        --python-version 3.12 \
        --only-binary=:all:
      # Trim site-packages aggressively to stay well under the 250MB
      # uncompressed Lambda layer cap and keep the upload fast.
      #   - boto3/botocore/s3transfer: already present in the Lambda runtime.
      #   - zstandard: langsmith optional compression backend; falls back to gzip.
      #   - tests/, __pycache__, *.pyc: never needed at runtime.
      find "$BUILD_DIR" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
      find "$BUILD_DIR" -name '*.pyc' -delete 2>/dev/null || true
      find "$BUILD_DIR" -name 'tests' -type d -prune -exec rm -rf {} + 2>/dev/null || true
      rm -rf \
        "$BUILD_DIR"/boto3 "$BUILD_DIR"/boto3-*.dist-info \
        "$BUILD_DIR"/botocore "$BUILD_DIR"/botocore-*.dist-info \
        "$BUILD_DIR"/s3transfer "$BUILD_DIR"/s3transfer-*.dist-info \
        "$BUILD_DIR"/zstandard "$BUILD_DIR"/zstandard-*.dist-info 2>/dev/null || true
    EOT
  }
}

data "archive_file" "lambda_layer_zip" {
  depends_on  = [terraform_data.lambda_layer_build]
  type        = "zip"
  source_dir  = "${path.module}/.layer-build"
  output_path = "${path.module}/lambda-layer.zip"
}

resource "aws_lambda_layer_version" "deps" {
  filename            = data.archive_file.lambda_layer_zip.output_path
  source_code_hash    = data.archive_file.lambda_layer_zip.output_base64sha256
  layer_name          = "${var.project_name}-deps"
  compatible_runtimes = ["python3.12"]
  description         = "LangGraph + LangChain + LangSmith and transitive deps (x86_64-manylinux2014)"
}

# ── Lambda packaging ──────────────────────────────────────────────────────────
# Zips the full backend/ directory. boto3 is already in the Lambda runtime and
# langchain/langgraph/langsmith live in the layer above.
# Excludes the uv virtual env, cache, and test files — these must not be deployed.

data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/../../../backend"
  output_path = "${path.module}/lambda.zip"

  excludes = [
    ".venv",
    ".local-vectorstore", # local ChromaDB store — never used in prod
    ".local-vectorstore/**",
    "modules", # defensive: prevents any stray tf build artefacts from leaking in
    "modules/**",
    "__pycache__",
    "*.pyc",
    "test_*.py",  # test runners — committed to git, not needed in Lambda
    "*_local.py", # local-only scripts — committed to git, not needed in Lambda
    "pyproject.toml",
    "uv.lock",
  ]
}

# ── Lambda function ───────────────────────────────────────────────────────────

resource "aws_lambda_function" "handler" {
  function_name    = "${var.project_name}-handler"
  role             = aws_iam_role.lambda_exec.arn
  runtime          = "python3.12"
  handler          = "handler.lambda_handler"
  filename         = data.archive_file.lambda_zip.output_path
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  layers           = [aws_lambda_layer_version.deps.arn]
  architectures    = ["x86_64"]

  # 30s is well within the Bedrock KB p95 latency budget
  timeout     = 30
  memory_size = 512

  environment {
    variables = {
      ENV               = var.environment
      KNOWLEDGE_BASE_ID = var.knowledge_base_id
      GUARDRAIL_ID      = var.guardrail_id
      GUARDRAIL_VERSION = var.guardrail_version
      BEDROCK_MODEL_ID  = var.bedrock_model_id
      CHROMA_HOST       = var.chroma_host
      CHROMA_PORT       = var.chroma_port
      CHECKPOINTS_TABLE = var.checkpoints_table_name

      # LangSmith tracing. Flipped to "true" only when an SSM parameter is
      # wired in; the Lambda code fetches the key at cold start from SSM.
      LANGSMITH_TRACING               = var.langsmith_ssm_parameter_name == "" ? "false" : "true"
      LANGSMITH_PROJECT               = var.langsmith_project
      LANGSMITH_ENDPOINT              = var.langsmith_endpoint
      LANGSMITH_API_KEY_SSM_PARAMETER = var.langsmith_ssm_parameter_name
    }
  }
}
